#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Test.Resource", IsApplication=true)]

namespace Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int BirthCertCopy_Spinner = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int Building_Spinner = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int Cook_Spinner = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int DRINK_Spinner = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int Death_certificate = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int Death_register = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int Gender_Spinner = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int Light_Spinner = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int Literacy_Spinner = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int Marital_Spinner = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int RHOUSE_Spinner = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int Roof_Spinner = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int SchoolAttend_Spinner = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int SchoolHigh_Spinner = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int Tenure_Spinner = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int Wall_Spinner = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int WorkStatus_Spinner = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int pwd_status = 2131034120;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int census_leftdrawer = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int census_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int census_start = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int date = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EditableTextStyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int EditTextStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int interview = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LogoLogOut = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int LogoUser = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int passwordloginbutton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int searchbutton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int TextBorder = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int TextBorderBotton = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int TextBorderCurve = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int userloginbutton = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int ActLeftDrawer = 2131165185;
			
			// aapt resource value: 0x7f07001b
			public const int FlyOutContent = 2131165211;
			
			// aapt resource value: 0x7f070052
			public const int FlyOutMenu = 2131165266;
			
			// aapt resource value: 0x7f070050
			public const int Layout1 = 2131165264;
			
			// aapt resource value: 0x7f070058
			public const int MenuInterviewer = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int MenuLogout = 2131165273;
			
			// aapt resource value: 0x7f070057
			public const int MenuUserName = 2131165271;
			
			// aapt resource value: 0x7f07005a
			public const int TableLayout1 = 2131165274;
			
			// aapt resource value: 0x7f07005c
			public const int TableLayout2 = 2131165276;
			
			// aapt resource value: 0x7f070006
			public const int btnAddAddress = 2131165190;
			
			// aapt resource value: 0x7f070024
			public const int btnAddaddress = 2131165220;
			
			// aapt resource value: 0x7f07003a
			public const int btnAddmember = 2131165242;
			
			// aapt resource value: 0x7f07005b
			public const int btnDone = 2131165275;
			
			// aapt resource value: 0x7f070060
			public const int btnScanBox = 2131165280;
			
			// aapt resource value: 0x7f07001f
			public const int btnSync = 2131165215;
			
			// aapt resource value: 0x7f070069
			public const int btnlogin = 2131165289;
			
			// aapt resource value: 0x7f07002c
			public const int checkBox1 = 2131165228;
			
			// aapt resource value: 0x7f07004f
			public const int datepicker = 2131165263;
			
			// aapt resource value: 0x7f070064
			public const int debenhams = 2131165284;
			
			// aapt resource value: 0x7f070002
			public const int frameLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070020
			public const int horizontalScrollView1 = 2131165216;
			
			// aapt resource value: 0x7f070087
			public const int imageView1 = 2131165319;
			
			// aapt resource value: 0x7f070066
			public const int imgLogo = 2131165286;
			
			// aapt resource value: 0x7f070010
			public const int lblBarangay = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int lblBuildingSerail = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int lblCity = 2131165198;
			
			// aapt resource value: 0x7f070019
			public const int lblContact = 2131165209;
			
			// aapt resource value: 0x7f070015
			public const int lblFname = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int lblLname = 2131165207;
			
			// aapt resource value: 0x7f07005d
			public const int lblPo = 2131165277;
			
			// aapt resource value: 0x7f07000c
			public const int lblProvince = 2131165196;
			
			// aapt resource value: 0x7f070062
			public const int lblSKU = 2131165282;
			
			// aapt resource value: 0x7f070004
			public const int lbladdresstitle = 2131165188;
			
			// aapt resource value: 0x7f070033
			public const int lblbday = 2131165235;
			
			// aapt resource value: 0x7f070041
			public const int lblbuilding = 2131165249;
			
			// aapt resource value: 0x7f07004b
			public const int lblcook = 2131165259;
			
			// aapt resource value: 0x7f070035
			public const int lblcopybday = 2131165237;
			
			// aapt resource value: 0x7f070049
			public const int lbldrink = 2131165257;
			
			// aapt resource value: 0x7f070031
			public const int lblgender = 2131165233;
			
			// aapt resource value: 0x7f070047
			public const int lbllight = 2131165255;
			
			// aapt resource value: 0x7f070077
			public const int lblliteracy = 2131165303;
			
			// aapt resource value: 0x7f07002e
			public const int lbllname = 2131165230;
			
			// aapt resource value: 0x7f070037
			public const int lblmarital = 2131165239;
			
			// aapt resource value: 0x7f07006b
			public const int lblmname = 2131165291;
			
			// aapt resource value: 0x7f07007b
			public const int lbloccupation = 2131165307;
			
			// aapt resource value: 0x7f07007d
			public const int lblpwd = 2131165309;
			
			// aapt resource value: 0x7f070071
			public const int lblreligion = 2131165297;
			
			// aapt resource value: 0x7f07003e
			public const int lblrhouse = 2131165246;
			
			// aapt resource value: 0x7f070043
			public const int lblroof = 2131165251;
			
			// aapt resource value: 0x7f070073
			public const int lblschool = 2131165299;
			
			// aapt resource value: 0x7f070075
			public const int lblschoolhigh = 2131165301;
			
			// aapt resource value: 0x7f07004d
			public const int lbltenure = 2131165261;
			
			// aapt resource value: 0x7f070045
			public const int lblwall = 2131165253;
			
			// aapt resource value: 0x7f070079
			public const int lblworkstatus = 2131165305;
			
			// aapt resource value: 0x7f07000a
			public const int linaddinformationaddress = 2131165194;
			
			// aapt resource value: 0x7f070014
			public const int linaddinformationname = 2131165204;
			
			// aapt resource value: 0x7f070005
			public const int linbotton = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070021
			public const int linearLayout2 = 2131165217;
			
			// aapt resource value: 0x7f07002b
			public const int linearLayout3 = 2131165227;
			
			// aapt resource value: 0x7f070026
			public const int linowner = 2131165222;
			
			// aapt resource value: 0x7f07001d
			public const int linsearch = 2131165213;
			
			// aapt resource value: 0x7f070029
			public const int linstatus = 2131165225;
			
			// aapt resource value: 0x7f070025
			public const int lintextdetail = 2131165221;
			
			// aapt resource value: 0x7f070063
			public const int lvBox = 2131165283;
			
			// aapt resource value: 0x7f070027
			public const int lvladdress = 2131165223;
			
			// aapt resource value: 0x7f07003b
			public const int lvlageatdeath = 2131165243;
			
			// aapt resource value: 0x7f070028
			public const int lvlfullname = 2131165224;
			
			// aapt resource value: 0x7f07003c
			public const int lvlgender = 2131165244;
			
			// aapt resource value: 0x7f070023
			public const int lvlist = 2131165219;
			
			// aapt resource value: 0x7f07002a
			public const int lvlstatus = 2131165226;
			
			// aapt resource value: 0x7f07001c
			public const int menuHdrButton = 2131165212;
			
			// aapt resource value: 0x7f070088
			public const int myButton = 2131165320;
			
			// aapt resource value: 0x7f070009
			public const int relativeLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int relativeLayout2 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int scrollView1 = 2131165192;
			
			// aapt resource value: 0x7f07006f
			public const int spnbirthcert = 2131165295;
			
			// aapt resource value: 0x7f070042
			public const int spnbuilding = 2131165250;
			
			// aapt resource value: 0x7f07004c
			public const int spncook = 2131165260;
			
			// aapt resource value: 0x7f070036
			public const int spndeathcert = 2131165238;
			
			// aapt resource value: 0x7f07004a
			public const int spndrink = 2131165258;
			
			// aapt resource value: 0x7f070032
			public const int spngender = 2131165234;
			
			// aapt resource value: 0x7f070048
			public const int spnlight = 2131165256;
			
			// aapt resource value: 0x7f070078
			public const int spnliteracy = 2131165304;
			
			// aapt resource value: 0x7f070070
			public const int spnmarital = 2131165296;
			
			// aapt resource value: 0x7f07007e
			public const int spnpwd = 2131165310;
			
			// aapt resource value: 0x7f070038
			public const int spnregisterdeath = 2131165240;
			
			// aapt resource value: 0x7f07006d
			public const int spnrhouse = 2131165293;
			
			// aapt resource value: 0x7f070044
			public const int spnroof = 2131165252;
			
			// aapt resource value: 0x7f070074
			public const int spnschoolattendance = 2131165300;
			
			// aapt resource value: 0x7f070076
			public const int spnschoolhigh = 2131165302;
			
			// aapt resource value: 0x7f07004e
			public const int spntenure = 2131165262;
			
			// aapt resource value: 0x7f070000
			public const int spntest = 2131165184;
			
			// aapt resource value: 0x7f070046
			public const int spnwall = 2131165254;
			
			// aapt resource value: 0x7f07007a
			public const int spnworkstatus = 2131165306;
			
			// aapt resource value: 0x7f070055
			public const int tableLayout1 = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int tableRow1 = 2131165270;
			
			// aapt resource value: 0x7f07005f
			public const int tableRow4 = 2131165279;
			
			// aapt resource value: 0x7f070053
			public const int textView1 = 2131165267;
			
			// aapt resource value: 0x7f07000b
			public const int textView2 = 2131165195;
			
			// aapt resource value: 0x7f070022
			public const int textView5 = 2131165218;
			
			// aapt resource value: 0x7f070011
			public const int txtBarangay = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int txtBuilding_no = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int txtCity = 2131165199;
			
			// aapt resource value: 0x7f07001a
			public const int txtContact = 2131165210;
			
			// aapt resource value: 0x7f070016
			public const int txtFname = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int txtLname = 2131165208;
			
			// aapt resource value: 0x7f07006a
			public const int txtPassword = 2131165290;
			
			// aapt resource value: 0x7f07000d
			public const int txtProvince = 2131165197;
			
			// aapt resource value: 0x7f070061
			public const int txtScanUpc = 2131165281;
			
			// aapt resource value: 0x7f070068
			public const int txtUserName = 2131165288;
			
			// aapt resource value: 0x7f070034
			public const int txtageatdeath = 2131165236;
			
			// aapt resource value: 0x7f07006e
			public const int txtbday = 2131165294;
			
			// aapt resource value: 0x7f070080
			public const int txtbirthcert = 2131165312;
			
			// aapt resource value: 0x7f07003f
			public const int txtcopydeathcert = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int txtdeathreg = 2131165248;
			
			// aapt resource value: 0x7f070030
			public const int txtexname = 2131165232;
			
			// aapt resource value: 0x7f07002d
			public const int txtfname = 2131165229;
			
			// aapt resource value: 0x7f070039
			public const int txtfulladdress = 2131165241;
			
			// aapt resource value: 0x7f07003d
			public const int txtgender = 2131165245;
			
			// aapt resource value: 0x7f070084
			public const int txtliteracy = 2131165316;
			
			// aapt resource value: 0x7f07002f
			public const int txtlname = 2131165231;
			
			// aapt resource value: 0x7f07005e
			public const int txtloadnumber = 2131165278;
			
			// aapt resource value: 0x7f070081
			public const int txtmarital = 2131165313;
			
			// aapt resource value: 0x7f07006c
			public const int txtmname = 2131165292;
			
			// aapt resource value: 0x7f07007c
			public const int txtoccupation = 2131165308;
			
			// aapt resource value: 0x7f070067
			public const int txtpassword = 2131165287;
			
			// aapt resource value: 0x7f070086
			public const int txtpwd = 2131165318;
			
			// aapt resource value: 0x7f070072
			public const int txtreligion = 2131165298;
			
			// aapt resource value: 0x7f07007f
			public const int txtrhouse = 2131165311;
			
			// aapt resource value: 0x7f070082
			public const int txtschoolattendance = 2131165314;
			
			// aapt resource value: 0x7f070083
			public const int txtschoolhigh = 2131165315;
			
			// aapt resource value: 0x7f07001e
			public const int txtsearch = 2131165214;
			
			// aapt resource value: 0x7f070051
			public const int txturl = 2131165265;
			
			// aapt resource value: 0x7f070065
			public const int txtusername = 2131165285;
			
			// aapt resource value: 0x7f070085
			public const int txtworkstatus = 2131165317;
			
			// aapt resource value: 0x7f070054
			public const int view2 = 2131165268;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int aspinnertest = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int LayAddress = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LayAddressAdd = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LayAddressList = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int LayAddressLists = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int LayDeathAdd = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int LayDeathList = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int LayDeathLists = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int LayDeathView = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int LayHousing = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int LayInputDATE = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int LayInputURL = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int LayLeftDrawer = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int LayLoadListsDetail = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int LayLogin = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int LayNameAdd = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int LayNameList = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int LayNameLists = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int LayNameView = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int LayStart = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int Main = 2130968596;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
